[tool.black]
    line-length = 100


#####################################
# Coverage options
#####################################
[tool.coverage.run]
    source = ["."]
    omit = [
        "*/tests/*",
        "*.yml",
        "*.json",
    ]

# https://coverage.readthedocs.io/en/v4.5.x/config.html#xml
[tool.coverage.xml]
    package_depth = 1


[tool.isort]
    ensure_newline_before_comments = true
    force_sort_within_sections = true
    include_trailing_comma = true
    skip_glob = ["**/node_modules/*", "**/tmp/*", "**/.venv/*", "**/docs/*"]
    use_parentheses = true


[tool.mypy]
    python_version = 3.8
    disallow_untyped_defs = true
    ignore_missing_imports = true
    warn_return_any = true
    warn_unused_configs = true
    exclude = [
        "^.venv/*",
        "^tests/*",
        "^tmp/*",
    ]
[[tool.mypy.overrides]]
    module = [
        "tests.*",
    ]
    disallow_untyped_defs = false


[tool.pytest.ini_options]
    addopts = "-rsxX -l --tb=short --strict-markers"
    # testケースの走査から除外したいpathを指定
    # norecursedirs = .* build CVS dist src *.egg
    testpaths = "tests"
    xfail_strict = true

    # The -W flag can be passed to control which warnings will be displayed or even turn them into errors:
    # How to use: $ pytest -vv -W error::FutureWarning
    # https://docs.pytest.org/en/latest/warnings.html

    # filterwarnings = [
    #     "ignore::pandas.errors.PerformanceWarning",
    #     "ignore::pandas.core.common.SettingWithCopyWarning",
    # ]
