name: prepare dependencies

# inputs:
#   some_env:
#     description: "some env passed from workflows"
#     required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install pipenv
      run: |
        pip install pipenv
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v2
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        pipenv lock --dev -r > requirements.txt
        pip install -r requirements.txt
